### ISSUE TITLE
Zero weights make first item to always get picked

### ISSUE THREAD

**Issue by aayush-plivo** [smallnest/weighted#11]
Just wanted to confirm if this is the desired behavior or is an edge case missed:

```go
package main

import (
	"fmt"
	"github.com/smallnest/weighted"
)

func main() {
	w := &weighted.SW{}
	w.Add("a", 0)
	w.Add("b", 0)

	for i := 0; i < 10; i++ {
		fmt.Printf("%s ", w.Next())
	}
}

// Output: a a a a a a a a a a
```

**Comment by smallnest** [comment]
weight must be greater than zero. The check should be added in this lib

**Comment by aayush-plivo** [comment]
> weight must be greater than zero. The check should be added in this lib

Can't we just treat it as equal weights (when all weights are zero) and distribute equally? @smallnest

**Comment by smallnest** [comment]
No. according to this algorithm, zero or negative are invalid
