### ISSUE TITLE
What's expect result when 0 weight

### ISSUE THREAD

**Issue by fooofei** [smallnest/weighted#13]
What's expect result of 
```go
w := &RRW{}
w.Add("s1", 0)
next = w.Next()
```
`next` will be `nil` or the only `s1` ?

And  then what's expect result of 
```go
w := &RRW{}
w.Add("s1", 0)
w.Add("s2", 0)
for {
   next = w.Next()
}

```

`next` will be `nil` `nil` `nil` ...  or `s1` `s2` `s1` `s2` ...  or `s1` `s1` `s1` ... 

And what's expect result of replace `RRW` to `SW` ?

**Comment by checkaayush** [comment]
@fooofei Please refer: https://github.com/smallnest/weighted/issues/11

**Comment by fooofei** [comment]
> @fooofei Please refer: #11

thanks
