### ISSUE TITLE
Documentation for goroutine-safe concurrent usage

### ISSUE THREAD

**Issue by checkaayush** [smallnest/weighted#14]
Some documentation around goroutine-safe concurrent usage of the library might help some beginners trying to use the library. Possible options:
- Adding example in README
- Adding an `_examples` directory in project root

@smallnest Let me know if this is something you'd be open to. Will be happy to create a PR.

**Comment by smallnest** [comment]
You are right. welcome to submit a pr

**Comment by checkaayush** [comment]
@smallnest Which option from the above do you prefer?

**Comment by smallnest** [comment]
You can add an example in _example. Thanks

**Comment by checkaayush** [comment]
Won't be able to pick this up due to other priorities. Closing this for now.
