### ISSUE TITLE
[Question] Is there any way to get  sequence of current_weights in round-robin?

### ISSUE THREAD

**Issue by dumindu** [smallnest/weighted#5]
Ex. 

```go
package main

import "fmt"

func ExampleRRW_Next() {
	w := &RRW{}
	w.Add("a", 5)
	w.Add("b", 2)
	w.Add("c", 3)

	for i := 0; i < 10; i++ {
		fmt.Printf("%s ", w.Next())
	}
}

```

always get `a a a c a b c a b c` sequence. 

Is there any way to get this sequence as an array, without looping a constant times like 10 in above example?

Thanks

**Comment by dumindu** [comment]
Hi,
Sorry! Still would like to know if anyone having an answer for this. 
At least a way to get this sequence array length?
Thanks

**Comment by smallnest** [comment]
I think you can use the sum of all weights as the array length （or lowest common multiple）

**Comment by dumindu** [comment]
@smallnest Got it, Thanks
